// Code Generated by Sidekick is for learning and experimentation purposes only.
const fs = require('fs');

// Read JSON file
const data = JSON.parse(fs.readFileSync('testcase2.json', 'utf8'));

const n = data.keys.n;
const k = data.keys.k;

// Parse roots: convert each value to decimal
let x = [];
let y = [];
let count = 0;
for (let key in data) {
    if (key === "keys") continue;
    count++;
    if (count > k) break; // Only first k roots
    const base = parseInt(data[key].base);
    const valueStr = data[key].value;
    // Use key as x value (or index), value as y value
    x.push(parseInt(key));
    y.push(parseInt(valueStr, base));
}

// Lagrange interpolation at x = 0
function lagrangeConstant(x, y) {
    const n = x.length;
    let c = 0;
    for (let i = 0; i < n; i++) {
        let li = 1;
        for (let j = 0; j < n; j++) {
            if (i !== j) {
                li *= (0 - x[j]) / (x[i] - x[j]);
            }
        }
        c += y[i] * li;
    }
    return Math.round(c); // If integer expected
}

const constantTerm = lagrangeConstant(x, y);
console.log('Constant term (c):', constantTerm);
